### ISSUE TITLE
Finish daily subscription script

### ISSUE THREAD

**Issue by GuthrieW** [GuthrieW/shl-trading-cards#50]

**Comment by GuthrieW** [comment]
1. Reset everyone's pack counter
2. Buy n packs based on subscription amount
3. Cancel subscriptions for users who don't have enough money

**Comment by DrunkenTeddy** [comment]
Good news, we no longer need to set counts to 0, the new view packsToday handles that all

**Comment by GuthrieW** [comment]
This is done now it just needs to happen at the correct time
