### ISSUE TITLE
Create regular backups of the admin_cards db

### ISSUE THREAD

**Issue by DrunkenTeddy** [GuthrieW/shl-trading-cards#86]
We need this backed up on the server and off of the server.

**Comment by luketd** [comment]
Should probably be every 24 hours with the amount of times it will be used daily

**Comment by DrunkenTeddy** [comment]
Weekly backups created, they run at 6 am UTC (2 am eastern) for the admin_cards db. It is backed up on the server (/backup) and on the simulationhockeysite@gmail.com google drive.
