### ISSUE TITLE
Infinite Loop while trying to log in from website

### ISSUE THREAD

**Issue by luketd** [GuthrieW/shl-trading-cards#91]
https://cdn.discordapp.com/attachments/573227685514575875/959830465777385482/2022-04-02_11-02-47.mp4

https://cdn.discordapp.com/attachments/573227685514575875/959831648294277170/RPReplay_Final1648912085.mp4

**Comment by GuthrieW** [comment]
We're going to replace our current auth system with the new one that Evan made so this will be obsolete anyway.
